### PR TITLE
Fix check for meeting overview

### LINKED ISSUE #63: Chair confusion
There is a display error in OQC: A person that is chair in a TC A and a normal member in a TC B, sees for every meeting in TC B all elements (e.g. Run, Conclude, Pause, Mark as Attending, Mark as Not attending, Reset, Checkboxes,...) as if he would be chair in TC B.
It looks like the template uses a wrong check.

### PR DESCRIPTION
**Pull request by koplas**
Check the roles for the current meeting and not all memberships.

### CODE REVIEW

**Review by JanHoefelmeyer — DISMISSED** [review]
LGTM & works

File: pkg/models/user.go [hunk 1]
```diff
@@ -153,9 +153,17 @@ func (u *User) Compare(o *User) int {
 	)
 }
 
+// MembershipByID return the membership for a given committee id.
+func (u *User) MembershipByID(id int64) *Membership {
+	if ms := u.FindMembershipCriterion(MembershipByID(id)); ms != nil {
```
Comment (s-l-teichmann) [inline pkg/models/user.go:158]: `return u.FindMembershipCriterion(MembershipByID(id))` should be enough.

**Review by s-l-teichmann — DISMISSED** [review]

**Review by JanHoefelmeyer — DISMISSED** [review]
Still LGTM & works

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works
